#!/usr/bin/env bash

## Copyright (C) 2020-2022 Encrypted Cicada <dev.varnit@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Files
CONFIG="-c $HOME/.config/eww/bar"

## Launch eww daemon and bar
if [[ ! `pidof eww` ]]; then
	eww ${CONFIG} daemon
	sleep 1
	eww ${CONFIG} open bar
fi
