#!/usr/bin/env bash

# This script display an appropriate volume icon according to the volume level

# Authors: Varnit Singh
# e-mail: dev.varnit@gmail.com
# License: GPL3

# Dependencies: `wireplumber`

icon() {
        if [[ "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | wc -l)" = "1" ]]; then

				VOLUME=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk -F ": " '{ printf "%d", $2*100 }')
                if [[ ${VOLUME} -ge 75 ]]; then
                        echo ""
                elif [[ ${VOLUME} -ge 50 ]]; then
                        echo ""
                elif [[ ${VOLUME} -ge 25 ]]; then
                        echo ""
                else
                        echo ""
                fi
        else
                echo ""
        fi
}

if [[ $1 = "-l" ]]; then
		VOLUME=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk -F ": " '{ printf "%d", $2*100 }')
        echo ${VOLUME}
elif [[ $1 = '-i' ]]; then
        icon
fi
