#!/usr/bin/env bash

DEVICE=$(nmcli device show | grep "GENERAL.DEVICE" | head -1 | awk -F ":" '{print $2}' | sed "s/\s//g")

STATUS=$(nmcli | grep ${DEVICE} | awk 'FNR == 1 {print $2}')
toggle() {
    if [ $STATUS == "connected" ]; then
        nmcli radio wifi off
        notify-send --icon=window-close --urgency=normal "Wi-Fi turned off"
    else
        nmcli radio wifi on
        notify-send --icon=checkmark --urgency=normal "Wi-Fi turned on"
    fi
}

status() {
    if [ $STATUS == "connected" ]; then
        echo "󰤨"
    else
        echo "󰤭"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
    elif [[ $1 == "--status" ]]; then
    status
fi
