#!/usr/bin/env bash

STATUS=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk -F " " '{print $3}')

toggle() {
    if [[ "$STATUS" = "[MUTED]" ]]; then
        wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
        notify-send --icon=volume-level-muted --urgency=normal "Sounds unmuted"
    else
        wpctl set-mute @DEFAULT_AUDIO_SINK@ 1
        notify-send --icon=volume-level-high --urgency=normal "Sounds muted"
    fi
}

status() {
    if [[ "$STATUS" = "[MUTED]" ]]; then
        echo "󰖁"
    else
        echo "󰕾"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
    elif [[ $1 == "--status" ]]; then
    status
fi
